---
- hosts: default
  become: yes
  roles:
    - role: ansible-role-simulate-amazon-linux-centos
    - role: ansible-role-apache2.4-amazon-linux
    - role: ansible-role-php7.3-fedora
    - role: ansible-role-heroku-cli-amazon-linux
    - role: ansible-role-japan-fedora
    - role: ansible-role-cleaning-amazon-linux
      tags:
        - cleaning
